spring:
  application:
    name: warehouse-inventory
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/warehouse}
    username: ${SPRING_DATASOURCE_USERNAME:warehouse}
    password: ${SPRING_DATASOURCE_PASSWORD:warehouse}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
